name: Build PicoW Firmware (Manual - Pre-Release)

on:
  workflow_dispatch:

jobs:
  build:
    if: github.ref == 'refs/heads/pre-release'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        adapter: [REON, STACKSMASHING]
        board: [pico_w, pico2_w]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake gcc-arm-none-eabi build-essential libnewlib-arm-none-eabi
    - name: Clone Pico SDK (v2.1.1)
      run: |
        git clone --depth 1 --branch 2.1.1 https://github.com/raspberrypi/pico-sdk.git
        cd pico-sdk
        git submodule update --init
    - name: Create build directory
      run: |
        mkdir -p build/${{ matrix.adapter == 'STACKSMASHING' && 'release/SmBoard' || 'release/REON' }}/${{ matrix.board == 'pico_w' && 'PicoW' || 'Pico2W' }}
    - name: Configure CMake
      run: |
        cd build/${{ matrix.adapter == 'STACKSMASHING' && 'release/SmBoard' || 'release/REON' }}/${{ matrix.board == 'pico_w' && 'PicoW' || 'Pico2W' }}
        cmake ../../../.. \
          -DADAPTER=${{ matrix.adapter }} \
          -DPICO_BOARD=${{ matrix.board }} \
          -DPICO_SDK_PATH=${{ github.workspace }}/pico-sdk \
          -DCMAKE_BUILD_TYPE=Release
    - name: Build firmware
      run: |
        cd build/${{ matrix.adapter == 'STACKSMASHING' && 'release/SmBoard' || 'release/REON' }}/${{ matrix.board == 'pico_w' && 'PicoW' || 'Pico2W' }}
        cmake --build . --parallel
        ls
        echo -----------------
        ls release
        echo -----------------
        ls release/${{ matrix.adapter == 'STACKSMASHING' && 'SmBoard' || 'REON' }}
        echo -----------------
        ls release/${{ matrix.adapter == 'STACKSMASHING' && 'SmBoard' || 'REON' }}/${{ matrix.board == 'pico_w' && 'PicoW' || 'Pico2W' }}
    - name: List files after build
      run: |
        find ./build -type f
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: firmware-${{ matrix.adapter }}-${{ matrix.board }}
        path: ./build/release/${{ matrix.adapter == 'STACKSMASHING' && 'SmBoard' || 'REON' }}/${{ matrix.board == 'pico_w' && 'PicoW' || 'Pico2W' }}/PicoAdapterGB_${{ matrix.board == 'pico_w' && 'PicoW' || 'Pico2W' }}${{ matrix.adapter == 'STACKSMASHING' && '_SmBoard' || '' }}.uf2

